/* generated by build_catalog.py — do not edit by hand */
window.TI84_CATALOG = {
  "totalPrograms": 156,
  "subjectAreas": 22,
  "completePrice": 79,
  "separateTotal": 248,
  "originalCount": 52,
  "companionCount": 104,
  "free": {
    "sku": "free",
    "name": "Free Starter Pack",
    "short": "Unit converter · Quadratics · Stats · Unit circle · Geometry",
    "best": "Trying it out on any course",
    "price": 0,
    "programs": [
      {
        "file": "unit_converter.py",
        "oncalc": "",
        "blurb": "Length, mass, pressure, temperature, energy."
      },
      {
        "file": "quadratic_solver.py",
        "oncalc": "",
        "blurb": "Real and complex roots with discriminant."
      },
      {
        "file": "descriptive_stats.py",
        "oncalc": "",
        "blurb": "Mean, median, mode, variance, standard deviation."
      },
      {
        "file": "unit_circle_reference.py",
        "oncalc": "",
        "blurb": "Exact trig values, reference angle, quadrant."
      },
      {
        "file": "shape_geometry_solver.py",
        "oncalc": "",
        "blurb": "2D area/perimeter, 3D volume/surface area."
      }
    ]
  },
  "bundles": [
    {
      "sku": "algebra",
      "name": "Algebra, Precalculus & Trigonometry",
      "short": "Quadratics · Matrices · Polynomials · Unit circle",
      "best": "College algebra, precalc, trig, geometry",
      "price": 19,
      "programs": [
        {
          "file": "quadratic_solver.py",
          "oncalc": "",
          "blurb": "Discriminant classification plus real or complex-conjugate roots written as a ± bi."
        },
        {
          "file": "quadratic_vertex_analyzer.py",
          "oncalc": "",
          "blurb": "Build a parabola from vertex + one point; returns both forms, domain/range, intercepts, behaviour."
        },
        {
          "file": "complex_number_calculator.py",
          "oncalc": "",
          "blurb": "Complex arithmetic, magnitude and argument, rectangular ↔ polar — done by hand, since there's no cmath."
        },
        {
          "file": "linear_system_solver.py",
          "oncalc": "",
          "blurb": "2×2 or 3×3 Gaussian elimination with partial pivoting; flags inconsistent or dependent systems."
        },
        {
          "file": "matrix_toolkit.py",
          "oncalc": "",
          "blurb": "Add, multiply, determinant and inverse for 2×2 and 3×3 matrices."
        },
        {
          "file": "polynomial_analyzer.py",
          "oncalc": "",
          "blurb": "Real zeros by bounded bisection, end behaviour, turning points — plus rational asymptotes and holes."
        },
        {
          "file": "sequences_series.py",
          "oncalc": "",
          "blurb": "Arithmetic and geometric nth terms, partial sums, ratios from two terms, infinite sums."
        },
        {
          "file": "log_exp_solver.py",
          "oncalc": "",
          "blurb": "Change of base, solving b^x = c and log_b(x) = c, log rules worked on your numbers, growth and decay."
        },
        {
          "file": "oblique_triangle_solver.py",
          "oncalc": "",
          "blurb": "Law of Sines and Cosines: SSS, SAS, ASA/AAS and the ambiguous SSA case with 0, 1 or 2 solutions."
        },
        {
          "file": "unit_circle_reference.py",
          "oncalc": "",
          "blurb": "All six trig functions with exact values named, reference angle, quadrant, sign pattern, identities."
        },
        {
          "file": "shape_geometry_solver.py",
          "oncalc": "",
          "blurb": "Area and perimeter for 2D shapes, volume and surface area for 3D solids."
        }
      ]
    },
    {
      "sku": "calculus",
      "name": "Calculus & Differential Equations",
      "short": "Derivatives · Integrals · Series · ODEs",
      "best": "Calc I/II/III, intro ODEs",
      "price": 12,
      "programs": [
        {
          "file": "derivative_numeric.py",
          "oncalc": "",
          "blurb": "Central-difference derivative at three step sizes so you can watch it stabilise."
        },
        {
          "file": "simpsons_rule.py",
          "oncalc": "",
          "blurb": "Composite Simpson's rule definite integral, auto-corrects an odd subinterval count."
        },
        {
          "file": "taylor_series.py",
          "oncalc": "",
          "blurb": "Taylor/Maclaurin terms and running partial sums for sin, cos, e^x, ln(1+x), compared to the exact value."
        },
        {
          "file": "newton_raphson.py",
          "oncalc": "",
          "blurb": "Root finder with a full iteration table and numerically estimated derivative."
        },
        {
          "file": "limit_evaluator.py",
          "oncalc": "",
          "blurb": "Two-sided numeric limit: evaluates f(c±ε) for shrinking ε and reports agreement."
        },
        {
          "file": "ode_solver_euler.py",
          "oncalc": "",
          "blurb": "First-order dy/dx = f(x,y) by Euler's method or Improved Euler (Heun), with a step table."
        }
      ]
    },
    {
      "sku": "stats",
      "name": "Statistics, Probability & Discrete Math",
      "short": "Confidence intervals · Hypothesis tests · Chi-square",
      "best": "Intro statistics, probability, discrete math",
      "price": 12,
      "programs": [
        {
          "file": "descriptive_stats.py",
          "oncalc": "",
          "blurb": "Mean, median, mode, range, and both sample and population variance/standard deviation."
        },
        {
          "file": "confidence_interval_hypothesis_test.py",
          "oncalc": "",
          "blurb": "One-sample z or t interval and hypothesis test, with the critical-value tables built in."
        },
        {
          "file": "combinatorics_probability.py",
          "oncalc": "",
          "blurb": "nPr, nCr and binomial probability from a short menu."
        },
        {
          "file": "chi_square_genetics.py",
          "oncalc": "",
          "blurb": "Chi-square goodness of fit against a preset or custom ratio, with critical values at 0.05 and 0.01."
        },
        {
          "file": "discrete_math_toolkit.py",
          "oncalc": "",
          "blurb": "Binary/octal/decimal/hex conversion, plus truth tables for a typed boolean expression."
        }
      ]
    },
    {
      "sku": "physics",
      "name": "Physics & Engineering",
      "short": "Kinematics · Circuits · Fluids · Thermo · Materials",
      "best": "Physics I/II, statics, circuits, thermo",
      "price": 19,
      "programs": [
        {
          "file": "kinematics_solver.py",
          "oncalc": "",
          "blurb": "SUVAT: choose the unknown of v₀, v, a, t, d, enter the rest, get the value and the formula used."
        },
        {
          "file": "projectile_motion.py",
          "oncalc": "",
          "blurb": "Time of flight, range and max height, with an optional on-screen trajectory sketch via ti_plotlib."
        },
        {
          "file": "statics_vectors.py",
          "oncalc": "",
          "blurb": "2D force resultant from magnitude/angle pairs, and torque about a point with rotation sense."
        },
        {
          "file": "vector3d_toolkit.py",
          "oncalc": "",
          "blurb": "3D dot and cross products, magnitude, angle between vectors, scalar and vector projection."
        },
        {
          "file": "ohms_law_circuits.py",
          "oncalc": "",
          "blurb": "Solve V/I/R/P from any two knowns, plus a series and parallel resistor combiner."
        },
        {
          "file": "rlc_impedance.py",
          "oncalc": "",
          "blurb": "X_L, X_C, impedance magnitude, phase angle and LC resonant frequency."
        },
        {
          "file": "fluid_mechanics_solver.py",
          "oncalc": "",
          "blurb": "Bernoulli between two points in a flow, and Reynolds number with a laminar/turbulent verdict."
        },
        {
          "file": "heat_transfer_calculator.py",
          "oncalc": "",
          "blurb": "Specific heat, latent heat, and the equilibrium temperature of two masses mixed together."
        },
        {
          "file": "ideal_gas_processes.py",
          "oncalc": "",
          "blurb": "Work, heat and ΔU for isothermal, isobaric, isochoric and adiabatic processes."
        },
        {
          "file": "carnot_efficiency.py",
          "oncalc": "",
          "blurb": "Carnot and actual engine efficiency, fridge and heat-pump COP, and a second-law sanity check."
        },
        {
          "file": "stress_strain.py",
          "oncalc": "",
          "blurb": "Stress, strain, Young's modulus, δ = FL/(AE), factor of safety, Poisson's ratio, material table."
        },
        {
          "file": "thermal_expansion.py",
          "oncalc": "",
          "blurb": "Linear, area and volume expansion, thermal stress in a restrained member, expansion gaps."
        },
        {
          "file": "orbital_mechanics_calculator.py",
          "oncalc": "",
          "blurb": "Orbital speed and period, escape velocity, and Kepler's Third Law with GM presets."
        }
      ]
    },
    {
      "sku": "chemistry",
      "name": "Chemistry & Exam Tools",
      "short": "Gas laws · Stoichiometry · pH · Kinetics · Drills",
      "best": "General chemistry + study drilling",
      "price": 15,
      "programs": [
        {
          "file": "ideal_gas_law.py",
          "oncalc": "",
          "blurb": "Solve PV = nRT for any variable, plus a combined gas law state-1 → state-2 solver."
        },
        {
          "file": "stoichiometry_molar_mass.py",
          "oncalc": "",
          "blurb": "Molar mass from element/count pairs using a built-in table, then mass ↔ moles."
        },
        {
          "file": "acid_base_calculator.py",
          "oncalc": "",
          "blurb": "pH/pOH from [H⁺] or [OH⁻] and back, plus Henderson-Hasselbalch buffer pH."
        },
        {
          "file": "reaction_kinetics.py",
          "oncalc": "",
          "blurb": "Zero-, first- and second-order half-life, [A] at time t, and time to reach a target [A]."
        },
        {
          "file": "unit_converter.py",
          "oncalc": "",
          "blurb": "Length, mass, pressure, temperature and energy conversions from a numbered menu."
        },
        {
          "file": "formula_flashcards.py",
          "oncalc": "",
          "blurb": "Self-quiz recall drill by subject with self-graded scoring. A memorisation aid, not an answer lookup."
        },
        {
          "file": "exam_countdown_drill.py",
          "oncalc": "",
          "blurb": "Countdown timer plus randomly generated arithmetic, estimation and percentage drills."
        }
      ]
    },
    {
      "sku": "biology",
      "name": "Biology & Lab Science",
      "short": "Punnett · Hardy-Weinberg · Dilutions · Growth",
      "best": "Intro bio, genetics, ecology, lab methods",
      "price": 12,
      "programs": [
        {
          "file": "punnett_square_solver.py",
          "oncalc": "",
          "blurb": "Monohybrid and dihybrid crosses with full genotype and phenotype ratios."
        },
        {
          "file": "hardy_weinberg.py",
          "oncalc": "",
          "blurb": "Allele and genotype frequencies three ways in, carrier frequency, and an equilibrium chi-square test."
        },
        {
          "file": "chi_square_genetics.py",
          "oncalc": "",
          "blurb": "Chi-square goodness of fit against a preset or custom ratio, with critical values at 0.05 and 0.01."
        },
        {
          "file": "population_growth.py",
          "oncalc": "",
          "blurb": "Exponential and logistic growth, doubling time, dN/dt, and the inflection point at K/2."
        },
        {
          "file": "dilution_calculator.py",
          "oncalc": "",
          "blurb": "C1V1 = C2V2 any way round, serial-dilution plans, and molarity ↔ moles ↔ grams."
        },
        {
          "file": "surface_area_volume.py",
          "oncalc": "",
          "blurb": "SA:V ratios and how they scale, Kleiber's law metabolic rate, and diffusion time from distance."
        }
      ]
    },
    {
      "sku": "finance",
      "name": "Finance & Business Math",
      "short": "TVM · Amortization · NPV/IRR · Break-even",
      "best": "Personal finance, business math, eng. economics",
      "price": 12,
      "programs": [
        {
          "file": "tvm_solver.py",
          "oncalc": "",
          "blurb": "Five-variable time value of money: give any four, get the fifth. Ordinary annuity or annuity due."
        },
        {
          "file": "loan_amortization.py",
          "oncalc": "",
          "blurb": "Level payment, full or yearly schedule, lifetime interest, and the effect of paying extra."
        },
        {
          "file": "compound_interest.py",
          "oncalc": "",
          "blurb": "Any compounding frequency including continuous, APR ↔ APY, and an honest two-account comparison."
        },
        {
          "file": "npv_irr.py",
          "oncalc": "",
          "blurb": "NPV, IRR by bisection, simple and discounted payback, profitability index, multiple-IRR warning."
        },
        {
          "file": "break_even_margin.py",
          "oncalc": "",
          "blurb": "Break-even units and revenue, contribution margin, target profit, margin of safety, margin vs markup."
        }
      ]
    },
    {
      "sku": "arcade",
      "name": "Arcade Pack",
      "short": "Snake · 2048 · Mines · Wordle · Lights Out",
      "best": "Games on the keypad",
      "price": 9,
      "programs": [
        {
          "file": "snake.py",
          "oncalc": "SNAKE",
          "blurb": "Turn-based snake on a 16x8 field."
        },
        {
          "file": "g2048.py",
          "oncalc": "G2048",
          "blurb": "2048 with arrow-key slides."
        },
        {
          "file": "minesweeper.py",
          "oncalc": "MINES",
          "blurb": "8x8 minesweeper."
        },
        {
          "file": "wordle.py",
          "oncalc": "WORDLE",
          "blurb": "5-letter word game."
        },
        {
          "file": "lights_out.py",
          "oncalc": "LIGHTS",
          "blurb": "5x5 Lights Out. Always solvable."
        }
      ]
    },
    {
      "sku": "classroom",
      "name": "Classroom & Everyday",
      "short": "Caller · GPA · flashcards · tip · wage · lab regression",
      "best": "Teachers, homework, daily calc",
      "price": 19,
      "programs": [
        {
          "file": "random_caller.py",
          "oncalc": "CALLER",
          "blurb": "Draw names from a hat; reset when empty"
        },
        {
          "file": "buzzer.py",
          "oncalc": "BUZZER",
          "blurb": "Quiz-bowl lockout (first key of 1–4 wins)"
        },
        {
          "file": "grade_curver.py",
          "oncalc": "CURVE",
          "blurb": "Add points, 10√x, or linear map; one score or a list"
        },
        {
          "file": "gpa_tracker.py",
          "oncalc": "GPA",
          "blurb": "Credit-weighted 4.0 GPA with +/- letters"
        },
        {
          "file": "srs_flashcards.py",
          "oncalc": "FLASH",
          "blurb": "Leitner boxes + starter STEM deck; add your own"
        },
        {
          "file": "fact_drill.py",
          "oncalc": "DRILL",
          "blurb": "10-question times, squares, or unit-circle drill"
        },
        {
          "file": "tip_split.py",
          "oncalc": "TIP",
          "blurb": "Tax, tip on pre-tax, even split"
        },
        {
          "file": "unit_price.py",
          "oncalc": "PRICE",
          "blurb": "Compare 2–3 sizes; cheapest per unit"
        },
        {
          "file": "pomodoro.py",
          "oncalc": "POMO",
          "blurb": "25/5 study timer (or custom minutes)"
        },
        {
          "file": "lab_regression.py",
          "oncalc": "LABREG",
          "blurb": "LSRL, r, r², residuals from (x, y) pairs"
        },
        {
          "file": "sigfig_trainer.py",
          "oncalc": "SIGFIG",
          "blurb": "Count sig figs, % error, 8-question quiz"
        },
        {
          "file": "date_math.py",
          "oncalc": "DATE",
          "blurb": "Days between dates, or add/subtract days"
        },
        {
          "file": "recipe_scale.py",
          "oncalc": "RECIPE",
          "blurb": "Scale ingredient amounts between servings"
        },
        {
          "file": "trip_fuel.py",
          "oncalc": "TRIP",
          "blurb": "Gallons, fuel cost, and drive time"
        },
        {
          "file": "wage_ot.py",
          "oncalc": "WAGE",
          "blurb": "Hourly pay with overtime and yearly estimate"
        },
        {
          "file": "decision.py",
          "oncalc": "DECIDE",
          "blurb": "Weighted decision matrix"
        },
        {
          "file": "markup.py",
          "oncalc": "MARKUP",
          "blurb": "Markup, margin, markdown"
        }
      ]
    },
    {
      "sku": "shop_hobby",
      "name": "Shop, Hobby & Tabletop",
      "short": "Plates · stairs · resistors · Morse · D&D",
      "best": "Shop math, hobbies, tabletop",
      "price": 15,
      "programs": [
        {
          "file": "plates.py",
          "oncalc": "PLATES",
          "blurb": "Barbell plates per side for a target weight"
        },
        {
          "file": "board_feet.py",
          "oncalc": "BOARD",
          "blurb": "Board-feet cut list"
        },
        {
          "file": "stair_stringer.py",
          "oncalc": "STAIR",
          "blurb": "Risers, treads, stringer length, angle"
        },
        {
          "file": "cover_mix.py",
          "oncalc": "COVER",
          "blurb": "Paint gallons and concrete bags"
        },
        {
          "file": "resistor_code.py",
          "oncalc": "RCODE",
          "blurb": "4-band color code and LED current-limit R"
        },
        {
          "file": "run_pace.py",
          "oncalc": "PACE",
          "blurb": "Pace, finish time, even splits"
        },
        {
          "file": "pixel_art.py",
          "oncalc": "PIXEL",
          "blurb": "8×16 doodle pad"
        },
        {
          "file": "exposure.py",
          "oncalc": "EXPOSE",
          "blurb": "Sunny-16 and exposure-triangle match"
        },
        {
          "file": "timer555.py",
          "oncalc": "T555",
          "blurb": "555 astable frequency/duty and monostable pulse"
        },
        {
          "file": "morse.py",
          "oncalc": "MORSE",
          "blurb": "Encode, decode, letter quiz"
        },
        {
          "file": "tap_tempo.py",
          "oncalc": "TEMPO",
          "blurb": "Tap ENTER for BPM"
        },
        {
          "file": "dnd_kit.py",
          "oncalc": "DND",
          "blurb": "Dice (`2d6+3`), initiative, HP, death saves"
        }
      ]
    },
    {
      "sku": "algebra_steps",
      "name": "Algebra Steps",
      "short": "Synthetic division · partial fractions · conics",
      "best": "Algebra II / college algebra steps",
      "price": 15,
      "programs": [
        {
          "file": "synthetic_div.py",
          "oncalc": "SYNTH",
          "blurb": "Synthetic division tableau, quotient, remainder"
        },
        {
          "file": "complete_square.py",
          "oncalc": "COMPSQ",
          "blurb": "Completing-the-square steps and vertex"
        },
        {
          "file": "partial_frac.py",
          "oncalc": "PARTIAL",
          "blurb": "Partial fractions over distinct or repeated linear factors"
        },
        {
          "file": "long_div.py",
          "oncalc": "LONGDIV",
          "blurb": "Integer long-division tableau"
        },
        {
          "file": "poly_div.py",
          "oncalc": "POLYDIV",
          "blurb": "Polynomial long division (coeffs high → low)"
        },
        {
          "file": "lin_prog.py",
          "oncalc": "LINPROG",
          "blurb": "2-variable LP at feasible corners"
        },
        {
          "file": "lagrange.py",
          "oncalc": "INTERP",
          "blurb": "Lagrange interpolation through points"
        },
        {
          "file": "rational_root.py",
          "oncalc": "RATROOT",
          "blurb": "Rational-root candidates and synthetic tests"
        },
        {
          "file": "binomial_exp.py",
          "oncalc": "BINEXP",
          "blurb": "Expand (ax+b)^n"
        },
        {
          "file": "conic.py",
          "oncalc": "CONIC",
          "blurb": "Classify Ax²+Bxy+Cy²+Dx+Ey+F=0"
        }
      ]
    },
    {
      "sku": "calc3",
      "name": "Calc Steps & Calc 3",
      "short": "Related rates · gradient · Hessian · line integrals",
      "best": "Calc I–III homework steppers",
      "price": 19,
      "programs": [
        {
          "file": "related_rates.py",
          "oncalc": "RATES",
          "blurb": "Sphere, cone, ladder, shadow, two-path templates"
        },
        {
          "file": "int_compare.py",
          "oncalc": "INTCOMP",
          "blurb": "Left/right/mid/trap/Simpson for f(x)"
        },
        {
          "file": "series_tests.py",
          "oncalc": "SERIES",
          "blurb": "nth-term, ratio, root (sample n)"
        },
        {
          "file": "arc_volume.py",
          "oncalc": "ARCVOL",
          "blurb": "Arc length, disk, and washer (numeric)"
        },
        {
          "file": "linearize.py",
          "oncalc": "DIFFLIN",
          "blurb": "Differentials and L(x) ≈ f(a)+f'(a)(x-a)"
        },
        {
          "file": "parametric.py",
          "oncalc": "PARAM",
          "blurb": "dy/dx and d²y/dx² for x(t), y(t)"
        },
        {
          "file": "gradient.py",
          "oncalc": "GRAD",
          "blurb": "Partials, gradient, directional derivative"
        },
        {
          "file": "hessian.py",
          "oncalc": "HESSIAN",
          "blurb": "D = fxx fyy − fxy² and min/max/saddle"
        },
        {
          "file": "double_int.py",
          "oncalc": "DBLINT",
          "blurb": "Midpoint double integral on a rectangle"
        },
        {
          "file": "curl_div.py",
          "oncalc": "CURLDIV",
          "blurb": "Numeric divergence and curl (2D / 3D)"
        },
        {
          "file": "line_int.py",
          "oncalc": "LINEINT",
          "blurb": "Scalar and vector line integrals"
        },
        {
          "file": "triple_int.py",
          "oncalc": "TRIPINT",
          "blurb": "Midpoint triple integral on a box"
        },
        {
          "file": "jacobian.py",
          "oncalc": "JACOB2",
          "blurb": "2D Jacobian and change-of-variables integral"
        }
      ]
    },
    {
      "sku": "diffeq",
      "name": "Differential Equations & Numerical",
      "short": "Laplace · variation of parameters · bisection",
      "best": "ODE course + root finding",
      "price": 15,
      "programs": [
        {
          "file": "char_eq.py",
          "oncalc": "CHARDE",
          "blurb": "Characteristic roots, solution type, IVP"
        },
        {
          "file": "integrating_factor.py",
          "oncalc": "IFACTOR",
          "blurb": "y′+Py=Q, μ and numeric y(x1)"
        },
        {
          "file": "phase_portrait.py",
          "oncalc": "PHASE",
          "blurb": "Trace–det classification of 2×2 systems"
        },
        {
          "file": "laplace.py",
          "oncalc": "LAPLACE",
          "blurb": "Table, L{y′,y″}, inverse, homogeneous IVP"
        },
        {
          "file": "exact_de.py",
          "oncalc": "EXACTDE",
          "blurb": "Exactness My=Nx and numeric potential F=C"
        },
        {
          "file": "var_param.py",
          "oncalc": "VARPAR",
          "blurb": "Variation of parameters for ay″+by′+cy=g"
        },
        {
          "file": "bisect_secant.py",
          "oncalc": "BISECT",
          "blurb": "Bisection and secant iteration tables"
        },
        {
          "file": "newton2.py",
          "oncalc": "NEWT2",
          "blurb": "Newton for two equations f(x,y)=g(x,y)=0"
        },
        {
          "file": "div_diff.py",
          "oncalc": "DIVDIFF",
          "blurb": "Newton divided-difference interpolant"
        }
      ]
    },
    {
      "sku": "linalg",
      "name": "Linear Algebra & Complex",
      "short": "RREF · Gram-Schmidt · Cauchy-Riemann",
      "best": "Lin alg, complex analysis",
      "price": 12,
      "programs": [
        {
          "file": "eigen2.py",
          "oncalc": "EIGEN",
          "blurb": "2×2 eigenvalues and eigenvectors"
        },
        {
          "file": "cramer.py",
          "oncalc": "CRAMER",
          "blurb": "Cramer's rule 2×2 and 3×3"
        },
        {
          "file": "det_inv.py",
          "oncalc": "DETINV",
          "blurb": "det 2×2/3×3 and inverse 2×2"
        },
        {
          "file": "vectors.py",
          "oncalc": "VECTORS",
          "blurb": "Mag, unit, dot, angle, projection"
        },
        {
          "file": "gram_lstsq.py",
          "oncalc": "GRAMLS",
          "blurb": "Gram–Schmidt and least squares"
        },
        {
          "file": "rref.py",
          "oncalc": "RREF",
          "blurb": "Row-reduce 2×3 / 3×3 / 3×4 with steps"
        },
        {
          "file": "cross3.py",
          "oncalc": "CROSS3",
          "blurb": "Cross product, triple product, torque"
        },
        {
          "file": "cauchy_riemann.py",
          "oncalc": "CRLOG",
          "blurb": "Cauchy–Riemann check, Log, exp"
        }
      ]
    },
    {
      "sku": "phys2",
      "name": "Physics Extras",
      "short": "Optics · relativity · SHM · Doppler · Bohr",
      "best": "Physics I/II extras beyond SUVAT",
      "price": 12,
      "programs": [
        {
          "file": "optics.py",
          "oncalc": "OPTICS",
          "blurb": "Thin lens, magnification, Snell"
        },
        {
          "file": "decay.py",
          "oncalc": "DECAY",
          "blurb": "Half-life, remaining, activity"
        },
        {
          "file": "relativity.py",
          "oncalc": "RELATIV",
          "blurb": "γ, time dilation, length, E, p"
        },
        {
          "file": "collide.py",
          "oncalc": "COLLIDE",
          "blurb": "1D elastic and inelastic collisions"
        },
        {
          "file": "shm.py",
          "oncalc": "SHM",
          "blurb": "Mass-spring period, vmax, energy"
        },
        {
          "file": "bohr.py",
          "oncalc": "BOHR",
          "blurb": "Hydrogen En and transition λ"
        },
        {
          "file": "doppler.py",
          "oncalc": "DOPPLER",
          "blurb": "Doppler shift, beats, and v=fλ"
        }
      ]
    },
    {
      "sku": "chem2",
      "name": "Chemistry Extras",
      "short": "ICE tables · Nernst · Beer-Lambert · empirical",
      "best": "Gen chem labs and electrochem",
      "price": 12,
      "programs": [
        {
          "file": "ph_tool.py",
          "oncalc": "PHTOOL",
          "blurb": "pH/pOH/[H+], Henderson–Hasselbalch"
        },
        {
          "file": "calorimetry.py",
          "oncalc": "CALOR",
          "blurb": "q=mcΔT and two-sample mix"
        },
        {
          "file": "empirical.py",
          "oncalc": "EMPIRIC",
          "blurb": "Empirical formula from g or %"
        },
        {
          "file": "nernst.py",
          "oncalc": "NERNST",
          "blurb": "E = E0 − (0.05916/n) log Q"
        },
        {
          "file": "beer_lambert.py",
          "oncalc": "BEERLM",
          "blurb": "Beer–Lambert A=εlc, %T, two-point slope"
        },
        {
          "file": "ice_table.py",
          "oncalc": "ICE",
          "blurb": "ICE table; type x or back-solve from one eq value"
        },
        {
          "file": "dim_analysis.py",
          "oncalc": "DIMAN",
          "blurb": "Conversion-factor chain"
        }
      ]
    },
    {
      "sku": "discrete",
      "name": "Visual Math, Stats Extras & CS",
      "short": "Slope field · ANOVA · Bayes · bases · Collatz",
      "best": "Visual calc, extra stats, CS, number theory",
      "price": 19,
      "programs": [
        {
          "file": "slope_field.py",
          "oncalc": "SLOPE",
          "blurb": "Text slope field for y′=f(x,y); optional RK4 curve `*`"
        },
        {
          "file": "rk4_solver.py",
          "oncalc": "RK4",
          "blurb": "RK4 vs Euler table for y′=f(x,y)"
        },
        {
          "file": "fourier_series.py",
          "oncalc": "FOURIER",
          "blurb": "Square-wave coefficients, s(x), text plot"
        },
        {
          "file": "monte_carlo.py",
          "oncalc": "MCPI",
          "blurb": "Monte Carlo π (quarter-circle darts)"
        },
        {
          "file": "prob_pad.py",
          "oncalc": "PROBPAD",
          "blurb": "Binomial, Poisson, geometric, normal"
        },
        {
          "file": "bayes.py",
          "oncalc": "BAYES",
          "blurb": "P(A\\|B) from prior and likelihoods"
        },
        {
          "file": "chi_gof.py",
          "oncalc": "CHIGOF",
          "blurb": "Chi-square GOF vs 0.05 critical values"
        },
        {
          "file": "stat2.py",
          "oncalc": "STAT2",
          "blurb": "χ² independence and two-sample t"
        },
        {
          "file": "anova.py",
          "oncalc": "ANOVA",
          "blurb": "One-way ANOVA for 2–3 groups"
        },
        {
          "file": "base_convert.py",
          "oncalc": "BASES",
          "blurb": "Dec/bin/hex, 8-bit two's complement, ASCII"
        },
        {
          "file": "truth_table.py",
          "oncalc": "TRUTH",
          "blurb": "2–3 variable truth table (`and` / `or` / `not`)"
        },
        {
          "file": "sort_viz.py",
          "oncalc": "SORTVIZ",
          "blurb": "Step-through bubble / insertion sort"
        },
        {
          "file": "mod_toolkit.py",
          "oncalc": "MODULAR",
          "blurb": "GCD, inverse, CRT, a^b mod n"
        },
        {
          "file": "rsa_toy.py",
          "oncalc": "RSATOY",
          "blurb": "Primality and tiny RSA encrypt/decrypt"
        },
        {
          "file": "collatz.py",
          "oncalc": "COLLATZ",
          "blurb": "3n+1 sequence, peak, bar plot"
        },
        {
          "file": "polar_de_moivre.py",
          "oncalc": "POLAR",
          "blurb": "Rect↔polar, De Moivre powers and roots"
        }
      ]
    }
  ],
  "complete": {
    "sku": "complete",
    "name": "Complete Toolkit",
    "short": "All 156 programs + master reference",
    "best": "Every subject and the arcade pack",
    "price": 79,
    "count": 156
  }
};
