#!/usr/bin/env python3
"""Convert TI-84 Plus CE Python Edition ``.py`` source files into ``.8xv`` Python AppVars.

A Python AppVar is an ordinary TI-8x variable file (``**TI83F*`` container, var type
``0x15``) whose variable data is a Python payload: a 2-byte little-endian payload
length, the 4-byte magic ``PYCD``, a metadata-record block terminated by ``0x00``,
and then the raw script bytes.

The layout implemented here was derived from, and byte-checked against, a Python
AppVar generated by TI's own TI-SmartView CE 5.3.0.384
(``testData/python_HELLO.8xv`` in adriweb/tivars_lib_cpp). See
``bundles/FILE_FORMAT_NOTES.md`` for the full write-up and verification status.

Standard library only, so it runs anywhere Python 3.8+ does.

Usage::

    python py_to_8xv.py input.py                       # -> input.8xv
    python py_to_8xv.py input.py -o OUT.8xv --name MYPROG
    python py_to_8xv.py --batch ../ --out ../8xv       # mirror a whole tree
    python py_to_8xv.py --batch ../ --out ../8xv --names varnames.json
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

# --- Container constants (TI-8x variable file) -------------------------------

FILE_SIGNATURE = b"**TI83F*"
EXPORT_BYTES = b"\x1a\x0a"
DEFAULT_PRODUCT_ID = 0x0A  # what TI-SmartView CE writes; PC-side hint only
COMMENT_LENGTH = 42
HEADER_LENGTH = 53  # signature(8) + export(2) + product id(1) + comment(42)
CHECKSUM_LENGTH = 2

TYPE_ID_APPVAR = 0x15
ENTRY_META_LENGTH = 0x000D  # 13 => "flash" entry header carrying version + archive flag
NAME_LENGTH = 8
ENTRY_HEADER_LENGTH = 17  # meta(2) + len(2) + type(1) + name(8) + ver(1) + flag(1) + len(2)

ARCHIVE_FLAG_ARCHIVED = 0x80
ARCHIVE_FLAG_RAM = 0x00

# --- Python AppVar payload constants ----------------------------------------

PY_MAGIC_CODE = b"PYCD"  # plain Python source
PY_MAGIC_SCRIPT = b"PYSC"  # alternate magic also recognised by the Python app
PY_MAGICS = (PY_MAGIC_CODE, PY_MAGIC_SCRIPT)
METADATA_TERMINATOR = 0x00
METADATA_TYPE_FILENAME = 0x01

# An entry's variable data (including its own 2-byte length prefix) must fit the
# 16-bit length fields with room for the entry header.
MAX_VAR_DATA_LENGTH = 65514
MAX_PAYLOAD_LENGTH = MAX_VAR_DATA_LENGTH - 2

# Soft limit: the CE Python app gives roughly 50 KB total to all user programs.
SOFT_SCRIPT_WARN_BYTES = 16 * 1024

VALID_NAME_RE = re.compile(r"^[A-Z][A-Z0-9]{0,7}$")


class ConversionError(Exception):
    """Raised when input cannot be converted into a structurally valid AppVar."""


# --- Name handling -----------------------------------------------------------


def validate_var_name(name: str) -> str:
    """Return ``name`` if it is a legal on-calculator variable name, else raise."""
    if not VALID_NAME_RE.match(name):
        raise ConversionError(
            f"{name!r} is not a legal on-calculator name: use 1-8 characters, "
            "A-Z and 0-9 only, starting with a letter"
        )
    return name


def derive_var_name(stem: str, taken: set | None = None) -> str:
    """Derive a legal 8-character on-calculator name from a source file stem.

    Non-alphanumerics are dropped, the result is uppercased and truncated to 8
    characters, and a numeric suffix is appended if ``taken`` already holds it.
    """
    cleaned = re.sub(r"[^A-Za-z0-9]", "", stem).upper()
    cleaned = cleaned.lstrip("0123456789")
    if not cleaned:
        raise ConversionError(f"cannot derive a variable name from {stem!r}")

    candidate = cleaned[:NAME_LENGTH]
    if taken is None or candidate not in taken:
        return validate_var_name(candidate)

    for suffix in range(2, 100):
        tag = str(suffix)
        candidate = (cleaned[: NAME_LENGTH - len(tag)] + tag)[:NAME_LENGTH]
        if candidate not in taken:
            return validate_var_name(candidate)

    raise ConversionError(f"could not find a free variable name for {stem!r}")


# --- Script normalisation ----------------------------------------------------


def normalize_script(raw: bytes) -> bytes:
    """Strip a UTF-8 BOM, convert line endings to LF, and force a trailing LF.

    TI's own converter emits LF-terminated source; CRLF would show up as stray
    characters in the on-calculator editor.
    """
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
    script = raw.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    if not script.endswith(b"\n"):
        script += b"\n"
    return script


# --- Payload / container construction ---------------------------------------

def encode_metadata_length(value: int) -> bytes:
    """Encode a metadata record length using the format's 7-bit continuation scheme."""
    if value <= 0:
        raise ConversionError("metadata record length must be positive")
    out = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if value:
            byte |= 0x80
        out.append(byte)
        if not value:
            break
    if len(out) > 2:
        raise ConversionError("metadata record is too large")
    return bytes(out)


def build_payload(script: bytes, magic: bytes = PY_MAGIC_CODE, filename: str | None = None) -> bytes:
    """Build the Python AppVar payload: magic, metadata block, then script bytes."""
    if magic not in PY_MAGICS:
        raise ConversionError("Python AppVar magic must be PYCD or PYSC")

    payload = bytearray(magic)
    if filename:
        encoded = filename.encode("ascii", "strict")
        payload += encode_metadata_length(len(encoded) + 1)
        payload.append(METADATA_TYPE_FILENAME)
        payload += encoded
    payload.append(METADATA_TERMINATOR)
    payload += script

    if len(payload) > MAX_PAYLOAD_LENGTH:
        raise ConversionError(
            f"payload is {len(payload)} bytes, over the {MAX_PAYLOAD_LENGTH}-byte limit"
        )
    return bytes(payload)


def build_8xv(
    script: bytes,
    name: str,
    comment: str = "Created by py_to_8xv.py",
    archived: bool = False,
    version: int = 0,
    product_id: int = DEFAULT_PRODUCT_ID,
    magic: bytes = PY_MAGIC_CODE,
    filename: str | None = None,
) -> bytes:
    """Build a complete ``.8xv`` file containing one Python AppVar entry."""
    validate_var_name(name)
    payload = build_payload(script, magic=magic, filename=filename)

    var_data = len(payload).to_bytes(2, "little") + payload
    if len(var_data) > MAX_VAR_DATA_LENGTH:
        raise ConversionError(f"variable data is {len(var_data)} bytes, over the limit")

    entry = bytearray()
    entry += ENTRY_META_LENGTH.to_bytes(2, "little")
    entry += len(var_data).to_bytes(2, "little")
    entry.append(TYPE_ID_APPVAR)
    entry += name.encode("ascii").ljust(NAME_LENGTH, b"\x00")
    entry.append(version & 0xFF)
    entry.append(ARCHIVE_FLAG_ARCHIVED if archived else ARCHIVE_FLAG_RAM)
    entry += len(var_data).to_bytes(2, "little")
    entry += var_data

    encoded_comment = comment.encode("ascii", "replace")[:COMMENT_LENGTH]

    out = bytearray()
    out += FILE_SIGNATURE
    out += EXPORT_BYTES
    out.append(product_id & 0xFF)
    out += encoded_comment.ljust(COMMENT_LENGTH, b"\x00")
    out += len(entry).to_bytes(2, "little")
    out += entry
    out += (sum(entry) & 0xFFFF).to_bytes(2, "little")
    return bytes(out)


# --- Parsing / structural validation ----------------------------------------


def parse_8xv(blob: bytes) -> dict:
    """Parse a ``.8xv`` Python AppVar, validating every length field and the checksum.

    Returns a dict describing the file. Raises `ConversionError` on any mismatch,
    so a successful parse is itself a structural check.
    """
    if len(blob) < HEADER_LENGTH + 2 + ENTRY_HEADER_LENGTH + CHECKSUM_LENGTH:
        raise ConversionError(f"file is too short to be a var file ({len(blob)} bytes)")

    if blob[:8] != FILE_SIGNATURE:
        raise ConversionError(f"bad file signature {blob[:8]!r}, expected {FILE_SIGNATURE!r}")
    if blob[8:10] != EXPORT_BYTES:
        raise ConversionError(f"bad export bytes {blob[8:10]!r}, expected {EXPORT_BYTES!r}")

    product_id = blob[10]
    comment = blob[11:HEADER_LENGTH].rstrip(b"\x00").decode("ascii", "replace")

    declared_data_length = int.from_bytes(blob[HEADER_LENGTH:HEADER_LENGTH + 2], "little")
    data_start = HEADER_LENGTH + 2
    data_end = data_start + declared_data_length
    expected_file_length = data_end + CHECKSUM_LENGTH
    if expected_file_length != len(blob):
        raise ConversionError(
            f"declared data length {declared_data_length} implies a {expected_file_length}-byte "
            f"file, but the file is {len(blob)} bytes"
        )

    entry = blob[data_start:data_end]
    stored_checksum = int.from_bytes(blob[data_end:data_end + CHECKSUM_LENGTH], "little")
    computed_checksum = sum(entry) & 0xFFFF
    if stored_checksum != computed_checksum:
        raise ConversionError(
            f"checksum mismatch: stored 0x{stored_checksum:04X}, computed 0x{computed_checksum:04X}"
        )

    meta_length = int.from_bytes(entry[0:2], "little")
    if meta_length != ENTRY_META_LENGTH:
        raise ConversionError(f"unexpected entry meta length {meta_length}, expected {ENTRY_META_LENGTH}")

    var_data_length = int.from_bytes(entry[2:4], "little")
    type_id = entry[4]
    if type_id != TYPE_ID_APPVAR:
        raise ConversionError(f"var type is 0x{type_id:02X}, expected 0x{TYPE_ID_APPVAR:02X} (AppVar)")

    name = entry[5:13].rstrip(b"\x00").decode("ascii", "replace")
    version = entry[13]
    archive_flag = entry[14]
    var_data_length_copy = int.from_bytes(entry[15:17], "little")
    if var_data_length != var_data_length_copy:
        raise ConversionError(
            f"the two variable-data length fields disagree: {var_data_length} vs {var_data_length_copy}"
        )

    var_data = entry[ENTRY_HEADER_LENGTH:]
    if len(var_data) != var_data_length:
        raise ConversionError(
            f"declared variable data length {var_data_length} != actual {len(var_data)}"
        )

    payload_length = int.from_bytes(var_data[0:2], "little")
    payload = var_data[2:]
    if payload_length != len(payload):
        raise ConversionError(
            f"declared payload length {payload_length} != actual {len(payload)}"
        )

    magic = bytes(payload[0:4])
    if magic not in PY_MAGICS:
        raise ConversionError(f"payload magic {magic!r} is not a Python AppVar magic (PYCD/PYSC)")

    records = []
    pos = 4
    while True:
        if pos >= len(payload):
            raise ConversionError("metadata terminator not found in payload")
        if payload[pos] == METADATA_TERMINATOR:
            pos += 1
            break
        record_length = 0
        shift = 0
        length_bytes = 0
        while True:
            if pos >= len(payload):
                raise ConversionError("truncated metadata record length")
            byte = payload[pos]
            pos += 1
            record_length |= (byte & 0x7F) << shift
            length_bytes += 1
            if not byte & 0x80:
                break
            shift += 7
            if length_bytes >= 2:
                raise ConversionError("metadata record length exceeds supported size")
        if record_length < 1 or pos + record_length - 1 > len(payload):
            raise ConversionError("truncated metadata record")
        record_type = payload[pos]
        record_data = bytes(payload[pos + 1:pos + record_length])
        pos += record_length
        records.append({"type": record_type, "data": record_data})

    script = bytes(payload[pos:])

    return {
        "product_id": product_id,
        "comment": comment,
        "name": name,
        "version": version,
        "archived": bool(archive_flag & ARCHIVE_FLAG_ARCHIVED),
        "archive_flag": archive_flag,
        "type_id": type_id,
        "declared_data_length": declared_data_length,
        "var_data_length": var_data_length,
        "payload_length": payload_length,
        "magic": magic,
        "metadata_records": records,
        "script": script,
        "checksum": stored_checksum,
    }


def self_check(blob: bytes, expected_name: str, expected_script: bytes) -> dict:
    """Parse ``blob`` back and confirm it reproduces the inputs exactly."""
    parsed = parse_8xv(blob)
    if parsed["name"] != expected_name:
        raise ConversionError(f"round-trip name mismatch: {parsed['name']!r} != {expected_name!r}")
    if parsed["script"] != expected_script:
        raise ConversionError("round-trip script mismatch: recovered bytes differ from the source")
    return parsed


# --- File-level conversion ---------------------------------------------------


def convert_file(
    src_path: str,
    out_path: str,
    name: str | None = None,
    comment: str = "Created by py_to_8xv.py",
    archived: bool = False,
    product_id: int = DEFAULT_PRODUCT_ID,
    taken: set | None = None,
) -> dict:
    """Convert one ``.py`` file to ``.8xv``, self-checking the result before writing."""
    with open(src_path, "rb") as handle:
        raw = handle.read()

    script = normalize_script(raw)
    try:
        script.decode("ascii")
    except UnicodeDecodeError as exc:
        raise ConversionError(
            f"{src_path} contains non-ASCII bytes at offset {exc.start}; the CE Python "
            "editor only reliably handles ASCII source"
        ) from exc

    stem = os.path.splitext(os.path.basename(src_path))[0]
    var_name = validate_var_name(name.upper()) if name else derive_var_name(stem, taken)

    blob = build_8xv(
        script,
        var_name,
        comment=comment,
        archived=archived,
        product_id=product_id,
    )
    parsed = self_check(blob, var_name, script)

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "wb") as handle:
        handle.write(blob)

    if taken is not None:
        taken.add(var_name)

    return {
        "source": src_path,
        "output": out_path,
        "name": var_name,
        "script_bytes": len(script),
        "file_bytes": len(blob),
        "checksum": parsed["checksum"],
        "oversized": len(script) > SOFT_SCRIPT_WARN_BYTES,
    }


# "qa" holds the desktop test harness, not calculator programs: it imports argparse,
# subprocess and friends, so converting it would ship files that cannot run on a TI-84.
DEFAULT_SKIP_DIRS = {
    "__pycache__", ".git", ".venv", "venv", "tools", "8xv", "bundles", "qa", "storefront",
}


def iter_sources(root: str, skip_dirs=(), only_dirs=()):
    """Yield ``.py`` files under ``root``, skipping caches, venvs, and this tool's folder.

    ``only_dirs`` restricts the walk to the named top-level subdirectories, which keeps
    a build reproducible even if unrelated ``.py`` files appear elsewhere in the tree.
    """
    skip = DEFAULT_SKIP_DIRS | set(skip_dirs)
    roots = [os.path.join(root, d) for d in only_dirs] if only_dirs else [root]

    for start in roots:
        for dirpath, dirnames, filenames in os.walk(start):
            dirnames[:] = sorted(d for d in dirnames if d not in skip and not d.startswith("."))
            for filename in sorted(filenames):
                if filename.endswith(".py"):
                    yield os.path.join(dirpath, filename)


def output_path_for(src_path: str, src_root: str, out_root: str, var_name: str, name_by_var: bool) -> str:
    """Work out where a converted file belongs, mirroring ``src_root``'s subfolders."""
    rel_dir = os.path.dirname(os.path.relpath(src_path, src_root))
    stem = var_name if name_by_var else os.path.splitext(os.path.basename(src_path))[0]
    return os.path.join(out_root, rel_dir, stem + ".8xv")


def convert_directory(
    src_root: str,
    out_root: str,
    names: dict | None = None,
    comment: str = "Created by py_to_8xv.py",
    archived: bool = False,
    product_id: int = DEFAULT_PRODUCT_ID,
    skip_dirs=(),
    only_dirs=(),
    name_by_var: bool = False,
) -> list:
    """Convert every ``.py`` under ``src_root`` into ``out_root``, mirroring subfolders."""
    names = names or {}
    taken: set = set()
    results = []
    for src_path in iter_sources(src_root, skip_dirs=skip_dirs, only_dirs=only_dirs):
        stem = os.path.splitext(os.path.basename(src_path))[0]
        var_name = validate_var_name(names[stem].upper()) if stem in names else derive_var_name(stem, taken)
        out_path = output_path_for(src_path, src_root, out_root, var_name, name_by_var)
        results.append(
            convert_file(
                src_path,
                out_path,
                name=var_name,
                comment=comment,
                archived=archived,
                product_id=product_id,
                taken=taken,
            )
        )
    return results


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert TI-84 Plus CE Python .py source into .8xv Python AppVars."
    )
    parser.add_argument("input", nargs="?", help="a single .py file to convert")
    parser.add_argument("-o", "--output", help="output .8xv path (single-file mode)")
    parser.add_argument("--name", help="on-calculator variable name (1-8 chars, A-Z0-9)")
    parser.add_argument("--batch", help="convert every .py under this directory")
    parser.add_argument("--out", help="output root directory (batch mode)")
    parser.add_argument("--names", help="JSON file mapping source stems to variable names")
    parser.add_argument(
        "--skip",
        action="append",
        default=[],
        metavar="DIR",
        help="extra directory name to exclude in batch mode (repeatable)",
    )
    parser.add_argument(
        "--only",
        action="append",
        default=[],
        metavar="DIR",
        help="restrict batch mode to this top-level subdirectory (repeatable)",
    )
    parser.add_argument(
        "--name-by-var",
        action="store_true",
        help="name output files after the on-calculator variable name instead of the source stem",
    )
    parser.add_argument("--comment", default="Created by py_to_8xv.py", help="42-char file comment")
    parser.add_argument("--archived", action="store_true", help="mark the AppVar as archived")
    parser.add_argument(
        "--product-id",
        type=lambda v: int(v, 0),
        default=DEFAULT_PRODUCT_ID,
        help="header product ID byte (default 0x0A, matching TI-SmartView CE output)",
    )
    args = parser.parse_args(argv)

    try:
        if args.batch:
            if not args.out:
                parser.error("--batch requires --out")
            names = {}
            if args.names:
                with open(args.names, "r", encoding="utf-8") as handle:
                    names = json.load(handle)
            results = convert_directory(
                args.batch,
                args.out,
                names=names,
                comment=args.comment,
                archived=args.archived,
                product_id=args.product_id,
                skip_dirs=args.skip,
                only_dirs=args.only,
                name_by_var=args.name_by_var,
            )
            for item in results:
                flag = "  [large]" if item["oversized"] else ""
                print(
                    f"{item['name']:<8}  {item['script_bytes']:>6} B src  "
                    f"{item['file_bytes']:>6} B 8xv  {item['output']}{flag}"
                )
            print(f"\nConverted {len(results)} file(s); all passed round-trip self-checks.")
        elif args.input:
            out_path = args.output or os.path.splitext(args.input)[0] + ".8xv"
            item = convert_file(
                args.input,
                out_path,
                name=args.name,
                comment=args.comment,
                archived=args.archived,
                product_id=args.product_id,
            )
            print(
                f"{item['name']:<8}  {item['script_bytes']} B src  "
                f"{item['file_bytes']} B 8xv  -> {item['output']}"
            )
        else:
            parser.error("provide an input file or --batch")
    except ConversionError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
