#!/usr/bin/env python3
"""Self-contained tests for ``py_to_8xv.py``. Run with ``python test_py_to_8xv.py``.

These are deliberately adversarial: as well as checking that valid input produces a
valid file, they corrupt one byte at a time and require the parser to notice. Without
that, "all files parsed successfully" would prove very little.

The one test that validates the format itself rather than our internal consistency is
``test_reference_reproduction``, which rebuilds a Python AppVar that TI's own
TI-SmartView CE 5.3.0.384 wrote and demands a byte-for-byte match. It needs TI's
``python_HELLO.8xv`` (from adriweb/tivars_lib_cpp ``testData/``); pass its path as the
first argument or the test is skipped.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from py_to_8xv import (  # noqa: E402
    ConversionError,
    build_8xv,
    derive_var_name,
    normalize_script,
    parse_8xv,
    validate_var_name,
)

REFERENCE_NAME = "HELLO"
REFERENCE_COMMENT = "Created by TI-Smartview CE 5.3.0.384"
REFERENCE_SCRIPT = b"import sys\nprint(sys.version)\n"

RESULTS = []


def record(name: str, ok: bool, detail: str = ""):
    RESULTS.append((name, ok, detail))
    print(f"  [{'ok' if ok else 'FAIL'}] {name}{(': ' + detail) if detail else ''}")


def expect(name: str, condition: bool, detail: str = ""):
    record(name, bool(condition), detail if not condition else "")


def test_reference_reproduction(reference_path: str | None):
    print("\nreference reproduction (TI-generated bytes)")
    if not reference_path or not os.path.exists(reference_path):
        print("  [skip] no TI reference file supplied")
        return

    with open(reference_path, "rb") as handle:
        expected = handle.read()

    parsed = parse_8xv(expected)
    expect("TI reference parses with our parser", parsed["script"] == REFERENCE_SCRIPT)

    rebuilt = build_8xv(
        REFERENCE_SCRIPT,
        REFERENCE_NAME,
        comment=REFERENCE_COMMENT,
        archived=False,
        version=parsed["version"],
        product_id=parsed["product_id"],
    )
    expect(
        "our builder reproduces TI's bytes exactly",
        rebuilt == expected,
        f"expected {expected.hex()} got {rebuilt.hex()}",
    )


def test_round_trip():
    print("\nround-trip fidelity")
    cases = {
        "ascii": b"print('hi')\n",
        "no trailing newline": b"x = 1",
        "crlf line endings": b"a = 1\r\nb = 2\r\n",
        "lone cr line endings": b"a = 1\rb = 2\r",
        "utf-8 bom": b"\xef\xbb\xbfprint(1)\n",
        "blank lines and indentation": b"def f():\n\n    return 1\n",
        "long script": b"# pad\n" * 2000,
    }
    for label, raw in cases.items():
        script = normalize_script(raw)
        blob = build_8xv(script, "TESTPROG")
        parsed = parse_8xv(blob)
        expect(f"round-trip: {label}", parsed["script"] == script)

    expect("normalize: CRLF becomes LF", normalize_script(b"a\r\nb") == b"a\nb\n")
    expect("normalize: BOM stripped", normalize_script(b"\xef\xbb\xbfa\n") == b"a\n")
    expect("normalize: trailing LF added", normalize_script(b"a") == b"a\n")
    expect("normalize: no duplicate trailing LF", normalize_script(b"a\n") == b"a\n")


def test_names():
    print("\nvariable name rules")
    for good in ["A", "HELLO", "QUADSOLV", "VECTOR3D", "P1"]:
        try:
            validate_var_name(good)
            expect(f"accepts {good!r}", True)
        except ConversionError as exc:
            expect(f"accepts {good!r}", False, str(exc))

    for bad in ["", "toolongname", "lower", "1START", "A_B", "A-B", "WITH SPC", "TOOLONGNM"]:
        try:
            validate_var_name(bad)
            expect(f"rejects {bad!r}", False, "was accepted")
        except ConversionError:
            expect(f"rejects {bad!r}", True)

    expect("derives QUADRATI from quadratic_solver", derive_var_name("quadratic_solver") == "QUADRATI")
    taken = {"QUADRATI"}
    second = derive_var_name("quadratic_vertex_analyzer", taken)
    expect("dedupes colliding derived names", second != "QUADRATI" and len(second) <= 8, second)
    expect("derived names are always legal", validate_var_name(second) == second)


def test_corruption_detected():
    print("\ncorruption detection (each mutates one byte and must be rejected)")
    good = build_8xv(b"print('hi')\n", "TESTPROG", comment="mutation test")
    parse_8xv(good)

    mutations = {
        "file signature": 0,
        "export bytes": 9,
        "declared data length": 53,
        "entry meta length": 55,
        "var data length field": 57,
        "var type byte": 59,
        "name field": 60,
        "var data length copy": 70,
        "payload length prefix": 72,
        "PYCD magic": 74,
        "metadata terminator": 78,
        "script byte": 82,
        "trailing checksum": len(good) - 1,
    }
    for label, offset in mutations.items():
        bad = bytearray(good)
        bad[offset] ^= 0xFF
        try:
            parse_8xv(bytes(bad))
            expect(f"detects corrupt {label}", False, f"byte 0x{offset:02X} flip went unnoticed")
        except ConversionError:
            expect(f"detects corrupt {label}", True)

    for label, blob in {
        "truncated file": good[:-1],
        "trailing garbage": good + b"\x00\x00",
        "empty file": b"",
        "non-var file": b"not a calculator file at all" * 4,
    }.items():
        try:
            parse_8xv(blob)
            expect(f"detects {label}", False, "was accepted")
        except ConversionError:
            expect(f"detects {label}", True)


def test_rejects_bad_input():
    print("\ninput validation")
    try:
        build_8xv(b"x\n", "lowercase")
        expect("rejects an illegal variable name", False, "was accepted")
    except ConversionError:
        expect("rejects an illegal variable name", True)

    try:
        build_8xv(b"#" * 70000, "TOOBIG")
        expect("rejects an oversized script", False, "was accepted")
    except ConversionError:
        expect("rejects an oversized script", True)


def main() -> int:
    reference = sys.argv[1] if len(sys.argv) > 1 else None
    test_reference_reproduction(reference)
    test_round_trip()
    test_names()
    test_corruption_detected()
    test_rejects_bad_input()

    failed = [name for name, ok, _ in RESULTS if not ok]
    print(f"\n{len(RESULTS) - len(failed)}/{len(RESULTS)} checks passed")
    if failed:
        print("FAILED:")
        for name in failed:
            print(f"  - {name}")
        return 1
    print("All tests passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
